# -*- mode: ruby -*-
# vi: set ft=ruby :

# Server
SERVER_NAME = 'aerraghaS'
SERVER_IP = '192.168.42.110'

# Server Worker
SERVER_WORKER_NAME = 'aerraghaSW'
SERVER_WORKER_IP = '192.168.42.111'

# System config
BOX = 'centos/7'
MEMORY = 1024
CPU = 1


Vagrant.configure("2") do |config|
  
  config.vm.box = BOX
  config.vbguest.installer_options = { allow_kernel_upgrade: true }

  # Server
  config.vm.define SERVER_NAME do |server|
    server.vm.hostname = SERVER_NAME
    server.vm.network :private_network, ip: SERVER_IP
    server.vm.synced_folder ".", "/vagrant", type: "virtualbox"
    server.vm.provision "shell", privileged: true, path: 'scripts/server.sh', args: [SERVER_IP]
    server.vm.provider "virtualbox" do |vb|
      vb.name = SERVER_NAME
      vb.memory = MEMORY
      vb.cpus = CPU
    end  
  end

  # Server Worker
  config.vm.define SERVER_WORKER_NAME do |worker|
    worker.vm.hostname = SERVER_WORKER_NAME
    worker.vm.network :private_network, ip: SERVER_WORKER_IP
    worker.vm.synced_folder ".", "/vagrant", type: "virtualbox"
    worker.vm.provision "shell", privileged: true, path: 'scripts/worker.sh', args: [SERVER_WORKER_IP]
    worker.vm.provider "virtualbox" do |vb|
      vb.name = SERVER_WORKER_NAME
      vb.memory = MEMORY
      vb.cpus = CPU
    end
  end

end
